export const GITHUB_MOST_STARRED_REPO_REQUEST =
  'GITHUB_MOST_STARRED_REPO_REQUEST'
export const GITHUB_MOST_STARRED_REPO_FAIL = 'GITHUB_MOST_STARRED_REPO_FAIL'
export const GITHUB_MOST_STARRED_REPO_SUCCESS =
  'GITHUB_MOST_STARRED_REPO_SUCCESS'
